name: eskalate_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  logger: ^2.5.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  equatable: ^2.0.7
  shared_preferences: ^2.3.3
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
